language: generic 
sudo: required
services:
  - docker

before_install:

script:


after_success:
    - docker build -t stephanrotolante/node-service ./service/node-service
    # - docker build -t stephanrotolante/nginx-node-service ./service/nginx

    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - docker push stephanrotolante/node-service


deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-west-2
    app: node-service
    env: NodeService-env
    bucket_name: elasticbeanstalk-us-west-2-777758686357
    bucket_path: node-service
    on:
        branch: master
    access_key_id: $AWS_ID
    secret_access_key: $AWS_SECRET