name: My test

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job 1 - checking the file structure
    steps:
    - uses: actions/checkout@v2
    - name: See file struture
      run: ls
    - name: See file struture
    run: cd ./service/node-service/
    - name: set environment variable
      run: package='package.json'
    - name: Hello world action step
      id: hello
      uses: stephanrotolante/update-version@master
      with:
        who-to-greet: 'Stephan'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
  second_job:
    runs-on: ubuntu-latest
    name: Job 2 - running extra commands
    steps:
      - name: we are running more commands
        run: exit